---
title: "Session 6: Homework 3"
author: "Group A17"
date: "2020-10-21"
output:
  html_document:
    theme: flatly
    highlight: zenburn
    number_sections: yes
    toc: yes
    toc_float: yes
    code_folding: show
---

<script src="index_files/kePrint/kePrint.js"></script>
<link href="index_files/lightable/lightable.css" rel="stylesheet" />


<div id="q1-youth-risk-behavior-surveillance" class="section level1">
<h1>Q1 Youth Risk Behavior Surveillance</h1>
<p>Every two years, the Centers for Disease Control and Prevention conduct the <a href="https://www.cdc.gov/healthyyouth/data/yrbs/index.htm">Youth Risk Behavior Surveillance System (YRBSS)</a> survey, where it takes data from high schoolers (9th through 12th grade), to analyze health patterns. You will work with a selected group of variables from a random sample of observations during one of the years the YRBSS was conducted.</p>
<div id="load-the-data" class="section level2">
<h2>Load the data</h2>
<p>This data is part of the <code>openintro</code> textbook and we can load and inspect it. There are observations on 13 different variables, some categorical and some numerical. The meaning of each variable can be found by bringing up the help file:</p>
<p>?yrbss</p>
<pre class="r"><code>data(yrbss)
glimpse(yrbss)</code></pre>
<pre><code>## Rows: 13,583
## Columns: 13
## $ age                      &lt;int&gt; 14, 14, 15, 15, 15, 15, 15, 14, 15, 15, 15...
## $ gender                   &lt;chr&gt; &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;female&quot;, &quot;f...
## $ grade                    &lt;chr&gt; &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9&quot;, &quot;9...
## $ hispanic                 &lt;chr&gt; &quot;not&quot;, &quot;not&quot;, &quot;hispanic&quot;, &quot;not&quot;, &quot;not&quot;, &quot;n...
## $ race                     &lt;chr&gt; &quot;Black or African American&quot;, &quot;Black or Afr...
## $ height                   &lt;dbl&gt; NA, NA, 1.73, 1.60, 1.50, 1.57, 1.65, 1.88...
## $ weight                   &lt;dbl&gt; NA, NA, 84.4, 55.8, 46.7, 67.1, 131.5, 71....
## $ helmet_12m               &lt;chr&gt; &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;never&quot;, &quot;did n...
## $ text_while_driving_30d   &lt;chr&gt; &quot;0&quot;, NA, &quot;30&quot;, &quot;0&quot;, &quot;did not drive&quot;, &quot;did ...
## $ physically_active_7d     &lt;int&gt; 4, 2, 7, 0, 2, 1, 4, 4, 5, 0, 0, 0, 4, 7, ...
## $ hours_tv_per_school_day  &lt;chr&gt; &quot;5+&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;2&quot;, &quot;3&quot;, &quot;5+&quot;, &quot;5+&quot;, &quot;5...
## $ strength_training_7d     &lt;int&gt; 0, 0, 0, 0, 1, 0, 2, 0, 3, 0, 3, 0, 0, 7, ...
## $ school_night_hours_sleep &lt;chr&gt; &quot;8&quot;, &quot;6&quot;, &quot;&lt;5&quot;, &quot;6&quot;, &quot;9&quot;, &quot;8&quot;, &quot;9&quot;, &quot;6&quot;, &quot;...</code></pre>
<pre class="r"><code>skimr::skim(yrbss)</code></pre>
<table style='width: auto;'
        class='table table-condensed'>
<caption>
<span id="tab:unnamed-chunk-2">Table 1: </span>Data summary
</caption>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:left;">
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Name
</td>
<td style="text-align:left;">
yrbss
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of rows
</td>
<td style="text-align:left;">
13583
</td>
</tr>
<tr>
<td style="text-align:left;">
Number of columns
</td>
<td style="text-align:left;">
13
</td>
</tr>
<tr>
<td style="text-align:left;">
_______________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Column type frequency:
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
character
</td>
<td style="text-align:left;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
numeric
</td>
<td style="text-align:left;">
5
</td>
</tr>
<tr>
<td style="text-align:left;">
________________________
</td>
<td style="text-align:left;">
</td>
</tr>
<tr>
<td style="text-align:left;">
Group variables
</td>
<td style="text-align:left;">
None
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: character</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
min
</th>
<th style="text-align:right;">
max
</th>
<th style="text-align:right;">
empty
</th>
<th style="text-align:right;">
n_unique
</th>
<th style="text-align:right;">
whitespace
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
gender
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
1.00
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
grade
</td>
<td style="text-align:right;">
79
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
hispanic
</td>
<td style="text-align:right;">
231
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
2
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
race
</td>
<td style="text-align:right;">
2805
</td>
<td style="text-align:right;">
0.79
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
41
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
helmet_12m
</td>
<td style="text-align:right;">
311
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
text_while_driving_30d
</td>
<td style="text-align:right;">
918
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
13
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
hours_tv_per_school_day
</td>
<td style="text-align:right;">
338
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
12
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
</tr>
<tr>
<td style="text-align:left;">
school_night_hours_sleep
</td>
<td style="text-align:right;">
1248
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
7
</td>
<td style="text-align:right;">
0
</td>
</tr>
</tbody>
</table>
<p><strong>Variable type: numeric</strong></p>
<table>
<thead>
<tr>
<th style="text-align:left;">
skim_variable
</th>
<th style="text-align:right;">
n_missing
</th>
<th style="text-align:right;">
complete_rate
</th>
<th style="text-align:right;">
mean
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
p0
</th>
<th style="text-align:right;">
p25
</th>
<th style="text-align:right;">
p50
</th>
<th style="text-align:right;">
p75
</th>
<th style="text-align:right;">
p100
</th>
<th style="text-align:left;">
hist
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
age
</td>
<td style="text-align:right;">
77
</td>
<td style="text-align:right;">
0.99
</td>
<td style="text-align:right;">
16.16
</td>
<td style="text-align:right;">
1.26
</td>
<td style="text-align:right;">
12.00
</td>
<td style="text-align:right;">
15.0
</td>
<td style="text-align:right;">
16.00
</td>
<td style="text-align:right;">
17.00
</td>
<td style="text-align:right;">
18.00
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2582&gt;&lt;U+2585&gt;&lt;U+2585&gt;&lt;U+2587&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
height
</td>
<td style="text-align:right;">
1004
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
1.69
</td>
<td style="text-align:right;">
0.10
</td>
<td style="text-align:right;">
1.27
</td>
<td style="text-align:right;">
1.6
</td>
<td style="text-align:right;">
1.68
</td>
<td style="text-align:right;">
1.78
</td>
<td style="text-align:right;">
2.11
</td>
<td style="text-align:left;">
&lt;U+2581&gt;&lt;U+2585&gt;&lt;U+2587&gt;&lt;U+2583&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
weight
</td>
<td style="text-align:right;">
1004
</td>
<td style="text-align:right;">
0.93
</td>
<td style="text-align:right;">
67.91
</td>
<td style="text-align:right;">
16.90
</td>
<td style="text-align:right;">
29.94
</td>
<td style="text-align:right;">
56.2
</td>
<td style="text-align:right;">
64.41
</td>
<td style="text-align:right;">
76.20
</td>
<td style="text-align:right;">
180.99
</td>
<td style="text-align:left;">
&lt;U+2586&gt;&lt;U+2587&gt;&lt;U+2582&gt;&lt;U+2581&gt;&lt;U+2581&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
physically_active_7d
</td>
<td style="text-align:right;">
273
</td>
<td style="text-align:right;">
0.98
</td>
<td style="text-align:right;">
3.90
</td>
<td style="text-align:right;">
2.56
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
2.0
</td>
<td style="text-align:right;">
4.00
</td>
<td style="text-align:right;">
7.00
</td>
<td style="text-align:right;">
7.00
</td>
<td style="text-align:left;">
&lt;U+2586&gt;&lt;U+2582&gt;&lt;U+2585&gt;&lt;U+2583&gt;&lt;U+2587&gt;
</td>
</tr>
<tr>
<td style="text-align:left;">
strength_training_7d
</td>
<td style="text-align:right;">
1176
</td>
<td style="text-align:right;">
0.91
</td>
<td style="text-align:right;">
2.95
</td>
<td style="text-align:right;">
2.58
</td>
<td style="text-align:right;">
0.00
</td>
<td style="text-align:right;">
0.0
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
5.00
</td>
<td style="text-align:right;">
7.00
</td>
<td style="text-align:left;">
&lt;U+2587&gt;&lt;U+2582&gt;&lt;U+2585&gt;&lt;U+2582&gt;&lt;U+2585&gt;
</td>
</tr>
</tbody>
</table>
<p>Before you carry on with your analysis, it’s is always a good idea to check with <code>skimr::skim()</code> to get a feel for missing values, summary statistics of numerical variables, and a very rough histogram.</p>
</div>
<div id="exploratory-data-analysis" class="section level2">
<h2>Exploratory Data Analysis</h2>
<p>You will first start with analyzing the <code>weight</code> of participants in kilograms. Using visualization and summary statistics, describe the distribution of weights. How many observations are we missing weights from?</p>
<pre class="r"><code>sum(is.na(yrbss$weight))</code></pre>
<pre><code>## [1] 1004</code></pre>
<pre class="r"><code>data_tidy &lt;- yrbss %&gt;% 
  filter(weight != &quot;NA&quot;)

ggplot(data_tidy, mapping = aes(x=weight)) + 
  geom_density()+
  theme_minimal()+
  labs(title = &quot;Distribution of Weights&quot;, subtitle = &quot;Right-skewed distribution with high outliers&quot;, x = &quot;Weight (in Kg)&quot;, y = &quot;Density&quot;)+
  theme(plot.title = element_text(family = &quot;Times&quot;, face = &quot;bold&quot;, size = (20)),
          axis.title = element_text(family = &quot;Times&quot;, size = (12)),
          axis.text = element_text(family = &quot;Times&quot;, size = (12)))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-3-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>summary(data_tidy$weight)</code></pre>
<pre><code>##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    29.9    56.2    64.4    67.9    76.2   181.0</code></pre>
<p>Next, consider the possible relationship between a high schooler’s weight and their physical activity. Plotting the data is a useful first step because it helps us quickly visualize trends, identify strong associations, and develop research questions.</p>
<pre class="r"><code>ggplot(data_tidy, mapping = aes(x = weight, y = physically_active_7d))+
  geom_point()+
  theme_minimal()+
  labs(title = &quot;Relationship between weight and physical activity&quot;, subtitle = &quot;...&quot;, x = &quot;Weight (in Kg)&quot;, y = &quot;Days of physical activity per week&quot;)+
  theme(plot.title = element_text(family = &quot;Helvetica&quot;, face = &quot;bold&quot;, size = (20)),
          axis.title = element_text(family = &quot;Helvetica&quot;, size = (12)),
          axis.text = element_text(family = &quot;Helvetica&quot;, size = (12)))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-5-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Let’s create a new variable <code>physical_3plus</code>, which will be <code>yes</code> if they are physically active for at least 3 days a week, and <code>no</code> otherwise.</p>
<pre class="r"><code>yrbss &lt;- yrbss %&gt;% 
  mutate(physical_3plus = ifelse(physically_active_7d &gt;= 3, &quot;yes&quot;, &quot;no&quot;))

yrbss %&gt;% 
  filter(!is.na(physical_3plus)) %&gt;% 
  group_by(physical_3plus) %&gt;% 
  summarise(count = n()) %&gt;% 
  mutate(prop= count/sum(count))</code></pre>
<pre><code>## # A tibble: 2 x 3
##   physical_3plus count  prop
##   &lt;chr&gt;          &lt;int&gt; &lt;dbl&gt;
## 1 no              4404 0.331
## 2 yes             8906 0.669</code></pre>
<p>Can you provide a 95% confidence interval for the population proportion of high schools that are <em>NOT</em> active 3 or more days per week?</p>
<p>Make a boxplot of <code>physical_3plus</code> vs. <code>weight</code>. Is there a relationship between these two variables? What did you expect and why?</p>
<pre class="r"><code>yrbss_boxplot &lt;- yrbss %&gt;% 
  filter(!is.na(physical_3plus), !is.na(weight)) %&gt;%
  ggplot(aes(x=physical_3plus, y=weight)) +
  geom_boxplot() +
  theme_minimal() +
  theme(plot.title = element_text(face=&quot;bold&quot;)) +
  labs(title = &quot;Relationship between physical activity and weight&quot;, subtitle = &quot;People with higher level of physical activity are slightly heavier&quot;, y = &quot;Weight (in Kg)&quot;, x = &quot;Level of physical activity&quot;) +
  theme(plot.title = element_text(family = &quot;Helvetica&quot;, face = &quot;bold&quot;, size = (20)),
          axis.title = element_text(family = &quot;Helvetica&quot;, size = (12)),
          axis.text = element_text(family = &quot;Helvetica&quot;, size = (12))) +
  NULL

yrbss_boxplot</code></pre>
<p><img src="index_files/figure-html/boxplot-1.png" width="648" style="display: block; margin: auto;" />
&gt; We expect that people with higher level of physical activity weigh less than people who are more inactive. However, surprisingly, people who exercise more are heavier. This may be explained by the fact that muscles weigh more. Besides, from the outliers, we can see that people with an extremely heavy weight are those who exercise less than 3 days per week.</p>
</div>
<div id="confidence-interval" class="section level2">
<h2>Confidence Interval</h2>
<p>Boxplots show how the medians of the two distributions compare, but we can also compare the means of the distributions using either a confidence interval or a hypothesis test. Note that when we calculate the mean/SD, etc weight in these groups using the mean function, we must ignore any missing values by setting the <code>na.rm = TRUE</code>.</p>
<pre class="r"><code>yrbss %&gt;%
  group_by(physical_3plus) %&gt;%
  filter(!is.na(physical_3plus)) %&gt;% 
  summarise(mean_weight = mean(weight, na.rm = TRUE),
            sd_weight = sd(weight, na.rm=TRUE),
            count = n(),
            se_weight = sd_weight/sqrt(count),
            t_critical = qt(0.975, count-1), 
            margin_of_error = t_critical * se_weight,
            lower = mean_weight - t_critical * se_weight,
            upper = mean_weight + t_critical * se_weight
            )</code></pre>
<pre><code>## # A tibble: 2 x 9
##   physical_3plus mean_weight sd_weight count se_weight t_critical
##   &lt;chr&gt;                &lt;dbl&gt;     &lt;dbl&gt; &lt;int&gt;     &lt;dbl&gt;      &lt;dbl&gt;
## 1 no                    66.7      17.6  4404     0.266       1.96
## 2 yes                   68.4      16.5  8906     0.175       1.96
## # ... with 3 more variables: margin_of_error &lt;dbl&gt;, lower &lt;dbl&gt;, upper &lt;dbl&gt;</code></pre>
<p>There is an observed difference of about 1.77kg (68.44 - 66.67), and we notice that the two confidence intervals do not overlap. It seems that the difference is at least 95% statistically significant. Let us also conduct a hypothesis test.</p>
</div>
<div id="hypothesis-test-with-formula" class="section level2">
<h2>Hypothesis test with formula</h2>
<p>Write the null and alternative hypotheses for testing whether mean weights are different for those who exercise at least times a week and those who don’t.</p>
<p>Null hypothesis: mean weights are same
Alternative hypothesis: mean weights are different</p>
<pre class="r"><code>t.test(weight ~ physical_3plus, data = yrbss)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  weight by physical_3plus
## t = -5, df = 7479, p-value = 9e-08
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -2.42 -1.12
## sample estimates:
##  mean in group no mean in group yes 
##              66.7              68.4</code></pre>
</div>
<div id="hypothesis-test-with-infer" class="section level2">
<h2>Hypothesis test with <code>infer</code></h2>
<p>Next, we will introduce a new function, <code>hypothesize</code>, that falls into the infer workflow. You will use this method for conducting hypothesis tests.</p>
<p>But first, we need to initialize the test, which we will save as <code>obs_diff</code>.</p>
<pre class="r"><code>obs_diff &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Notice how you can use the functions specify and calculate again like you did for calculating confidence intervals. Here, though, the statistic you are searching for is the difference in means, with the order being yes - no != 0.</p>
<p>After you have initialized the test, you need to simulate the test on the null distribution, which we will save as null.</p>
<pre class="r"><code>null_dist &lt;- yrbss %&gt;%
  specify(weight ~ physical_3plus) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000, type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;yes&quot;, &quot;no&quot;))</code></pre>
<p>Here, <code>hypothesize</code> is used to set the null hypothesis as a test for independence, i.e., that there is no difference between the two population means. In one sample cases, the null argument can be set to <em>point</em> to test a hypothesis relative to a point estimate.</p>
<p>Also, note that the <code>type</code> argument within generate is set to permute, which is the argument when generating a null distribution for a hypothesis test.</p>
<p>We can visualize this null distribution with the following code:</p>
<pre class="r"><code>ggplot(data = null_dist, aes(x = stat)) +
  geom_histogram()</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-11-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>Now that the test is initialized and the null distribution formed, we can visualise to see how many of these null permutations have a difference of at least <code>obs_stat</code> of 1.77?</p>
<p>We can also calculate the p-value for your hypothesis test using the function <code>infer::get_p_value()</code>.</p>
<pre class="r"><code>null_dist %&gt;% visualize() +
  shade_p_value(obs_stat = obs_diff, direction = &quot;two-sided&quot;)</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-12-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>null_dist %&gt;%
  get_p_value(obs_stat = obs_diff, direction = &quot;two_sided&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<p>This the standard workflow for performing hypothesis tests.</p>
</div>
</div>
<div id="q2-imdb-ratings-differences-between-directors" class="section level1">
<h1>Q2 IMDB ratings: Differences between directors</h1>
<p>In the following I will explore whether the mean IMDB rating for Steven Spielberg and Tim Burton are the same or not.</p>
<p><img src="C:/Users/User/Desktop/Arun_Website/images/directors.png" width="100%" style="display: block; margin: auto;" /></p>
<blockquote>
<p>First, I reproduce the above graph.</p>
</blockquote>
<pre class="r"><code>movies &lt;- read_csv(here::here(&quot;data&quot;, &quot;movies.csv&quot;))
glimpse(movies)</code></pre>
<pre><code>## Rows: 2,961
## Columns: 11
## $ title               &lt;chr&gt; &quot;Avatar&quot;, &quot;Titanic&quot;, &quot;Jurassic World&quot;, &quot;The Ave...
## $ genre               &lt;chr&gt; &quot;Action&quot;, &quot;Drama&quot;, &quot;Action&quot;, &quot;Action&quot;, &quot;Action&quot;...
## $ director            &lt;chr&gt; &quot;James Cameron&quot;, &quot;James Cameron&quot;, &quot;Colin Trevor...
## $ year                &lt;dbl&gt; 2009, 1997, 2015, 2012, 2008, 1999, 1977, 2015,...
## $ duration            &lt;dbl&gt; 178, 194, 124, 173, 152, 136, 125, 141, 164, 93...
## $ gross               &lt;dbl&gt; 7.61e+08, 6.59e+08, 6.52e+08, 6.23e+08, 5.33e+0...
## $ budget              &lt;dbl&gt; 2.37e+08, 2.00e+08, 1.50e+08, 2.20e+08, 1.85e+0...
## $ cast_facebook_likes &lt;dbl&gt; 4834, 45223, 8458, 87697, 57802, 37723, 13485, ...
## $ votes               &lt;dbl&gt; 886204, 793059, 418214, 995415, 1676169, 534658...
## $ reviews             &lt;dbl&gt; 3777, 2843, 1934, 2425, 5312, 3917, 1752, 1752,...
## $ rating              &lt;dbl&gt; 7.9, 7.7, 7.0, 8.1, 9.0, 6.5, 8.7, 7.5, 8.5, 7....</code></pre>
<pre class="r"><code>selected_directors &lt;- movies %&gt;%
  
  select(director, rating) %&gt;%
  
  filter(director == &quot;Steven Spielberg&quot; | director == &quot;Tim Burton&quot;) %&gt;%
  
  group_by(director) %&gt;%
  
  summarize(avg = mean(rating), 
            sd = sd(rating), 
            count = n(),
            tstat = qt(0.975, count-1),
            se = sd/sqrt(count),
            lower_ci = avg - tstat*se, 
            upper_ci = avg + tstat*se) 

selected_directors %&gt;%
  
  kable() %&gt;%
  
  kable_classic()</code></pre>
<table class=" lightable-classic" style='font-family: "Arial Narrow", "Source Sans Pro", sans-serif; margin-left: auto; margin-right: auto;'>
<thead>
<tr>
<th style="text-align:left;">
director
</th>
<th style="text-align:right;">
avg
</th>
<th style="text-align:right;">
sd
</th>
<th style="text-align:right;">
count
</th>
<th style="text-align:right;">
tstat
</th>
<th style="text-align:right;">
se
</th>
<th style="text-align:right;">
lower_ci
</th>
<th style="text-align:right;">
upper_ci
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Steven Spielberg
</td>
<td style="text-align:right;">
7.57
</td>
<td style="text-align:right;">
0.695
</td>
<td style="text-align:right;">
23
</td>
<td style="text-align:right;">
2.07
</td>
<td style="text-align:right;">
0.145
</td>
<td style="text-align:right;">
7.27
</td>
<td style="text-align:right;">
7.87
</td>
</tr>
<tr>
<td style="text-align:left;">
Tim Burton
</td>
<td style="text-align:right;">
6.93
</td>
<td style="text-align:right;">
0.749
</td>
<td style="text-align:right;">
16
</td>
<td style="text-align:right;">
2.13
</td>
<td style="text-align:right;">
0.187
</td>
<td style="text-align:right;">
6.53
</td>
<td style="text-align:right;">
7.33
</td>
</tr>
</tbody>
</table>
<pre class="r"><code># Selecting Spielberg and Burton

selected_directors &lt;- movies %&gt;% 
  
  filter(director == &quot;Steven Spielberg&quot; | director == &quot;Tim Burton&quot;) %&gt;% 
  
  group_by(director) %&gt;% 
  
  summarise(
    mean = mean(rating),
    sd = sd(rating),
    count = n(),
    se = sd / sqrt(count),
    tstat = qt(0.975, count - 1),
    lower_ci = mean - tstat * se,
    upper_ci = mean + tstat * se) 

# Reproducing the plot

ggplot(selected_directors, aes(
                            x = mean,
                            y = reorder(director, mean))) +

# Adding area where confidence intervals overlap
  
  geom_rect(xmin = 7.27,
            xmax = 7.33,
            ymin = 0,
            ymax = 10,
            fill = &quot;grey&quot;,
            aes(alpha = 0.5)) +
  
# Adding points to plot the mean
  
  geom_point(aes(
            color = director),
            size = 4) +
  
  
# Adding confidence interval error bars

  geom_errorbar(aes(
                    xmin = lower_ci,
                    xmax = upper_ci,
                    colour = director,
                    fill = director),
                    width = 0.2,
                    size = 1.5) +
  
# Adding mean labels
  
  geom_text(aes(
            label = round(mean, 2)),
            size = 5,
            hjust = 0.4,
            vjust = -1) +
  
# Setting fill colors
  
  scale_fill_manual(values = c(&quot;#FA8072&quot;, &quot;#48D1CC&quot;)) +
  
# Adding confidence interval labels
  
  geom_text(aes(
                label = round(lower_ci, 1.4)),
                hjust = 4,
                vjust = - 1) +
  
  geom_text(aes(
                label = round(upper_ci, 1.4)),
                hjust = - 4,
                vjust = - 1) +
  
# Adding theme
  
  theme_bw() +
  
# Removing legend
  
  theme(legend.position = &quot;none&quot;) +
  
# Adding titles to plot and axes
  
  theme(plot.title = element_text(face = &quot;bold&quot;)) +
  
  labs(title = &quot;Do Spielberg and Burton have the same IMDB ratings?&quot;,
       subtitle = &quot;95% confidence intervals overlap&quot;,
       x = &quot;Mean IMDB ratings&quot;,
       y = &quot;&quot;) +
  
# Adjusting size
  
  theme(aspect.ratio=3.5/5) </code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-14-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>Now I will perform a hypothesis test with the hypotheses being:</p>
</blockquote>
<blockquote>
<p>Null hypothesis: There is no difference between the mean ratings for Spielberg and Burton</p>
</blockquote>
<blockquote>
<p>Alternative hypothesis: There is a difference between the mean ratings for Spielberg and Burton</p>
</blockquote>
<pre class="r"><code>selected_directors &lt;- movies %&gt;%
  select(director, rating) %&gt;%
  filter(director == &quot;Steven Spielberg&quot; | director == &quot;Tim Burton&quot;)
t.test(rating ~ director, selected_directors)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  rating by director
## t = 3, df = 31, p-value = 0.01
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  0.16 1.13
## sample estimates:
## mean in group Steven Spielberg       mean in group Tim Burton 
##                           7.57                           6.93</code></pre>
<blockquote>
<p>The above t test shows that we have to reject the null hypothesis as the p-value is equal to 0.01 and hence &lt; 0.05</p>
</blockquote>
<pre class="r"><code>set.seed(1234)

# Running a simulation with the infer package

hypothesis_test &lt;- selected_directors %&gt;%
  
  specify(rating ~ director) %&gt;%
  
# Null hypothesis is that there is no difference between the two population means
  
  hypothesise(null=&quot;independence&quot;) %&gt;%
  
  generate(reps=1000,
           type=&quot;permute&quot;) %&gt;%
  
# Obtaining difference in means with bootstrap function
  
  calculate(stat=&quot;diff in means&quot;,
            order = c(&quot;Steven Spielberg&quot;,&quot;Tim Burton&quot;))

difference_ratings &lt;- selected_directors %&gt;%
  
  specify(rating ~ director) %&gt;%
  
  calculate(stat = &quot;diff in means&quot;, order = c(&quot;Steven Spielberg&quot;,&quot;Tim Burton&quot;))

# Get p_Value through infer package

p_value &lt;- hypothesis_test %&gt;%
  
  get_p_value(obs_stat = difference_ratings,
              direction = &quot;both&quot;)

kbl(p_value, 
    col.names=c(&quot;p-value&quot;),
    caption=&quot;Null distribution&quot;) %&gt;%

kable_classic()</code></pre>
<table class=" lightable-classic" style='font-family: "Arial Narrow", "Source Sans Pro", sans-serif; margin-left: auto; margin-right: auto;'>
<caption>
<span id="tab:unnamed-chunk-16">Table 2: </span>Null distribution
</caption>
<thead>
<tr>
<th style="text-align:right;">
p-value
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:right;">
0.008
</td>
</tr>
</tbody>
</table>
<blockquote>
<p>The simulation-based test shows again that the p-value is &lt; the alpha value. Hence, we reject the null-hypothesis.</p>
</blockquote>
</div>
<div id="omega-group-plc--pay-discrimination" class="section level1">
<h1>Omega Group plc- Pay Discrimination</h1>
<div id="background" class="section level2">
<h2>Background</h2>
<p>At the last board meeting of Omega Group Plc., the headquarters of a large multinational company, the issue was raised that women were being discriminated in the company, in the sense that the salaries were not the same for male and female executives. A quick analysis of a sample of 50 employees (of which 24 men and 26 women) revealed that the average salary for men was about 8,700 higher than for women. This seemed like a considerable difference, so it was decided that a further analysis of the company salaries was warranted.</p>
<p>The objective is to find out whether there is indeed a significant difference between the salaries of men and women, and whether the difference is due to discrimination or whether it is based on another, possibly valid, determining factor.</p>
</div>
<div id="loading-the-data" class="section level2">
<h2>Loading the data</h2>
<pre class="r"><code>omega &lt;- read_csv(here::here(&quot;data&quot;, &quot;omega.csv&quot;))

# examine the data frame
glimpse(omega) </code></pre>
<pre><code>## Rows: 50
## Columns: 3
## $ salary     &lt;dbl&gt; 81894, 69517, 68589, 74881, 65598, 76840, 78800, 70033, ...
## $ gender     &lt;chr&gt; &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, &quot;male&quot;, ...
## $ experience &lt;dbl&gt; 16, 25, 15, 33, 16, 19, 32, 34, 1, 44, 7, 14, 33, 19, 24...</code></pre>
<blockquote>
<p>As shown above, the data set has 50 observations and 3 variables, i.e. salary, gender and work experience.</p>
</blockquote>
</div>
<div id="relationship-salary---gender" class="section level2">
<h2>Relationship Salary - Gender</h2>
<p>The data frame <code>omega</code> contains the salaries for the sample of 50 executives in the company. Let’s find out if we conclude that there is a significant difference between the salaries of the male and female executives.</p>
<pre class="r"><code># Summary Statistics of salary by gender
mosaic::favstats (salary ~ gender, data=omega) </code></pre>
<pre><code>##   gender   min    Q1 median    Q3   max  mean   sd  n missing
## 1 female 47033 60338  64618 70033 78800 64543 7567 26       0
## 2   male 54768 68331  74675 78568 84576 73239 7463 24       0</code></pre>
<pre class="r"><code># Dataframe with two rows (male-female) and having as columns gender, mean, SD, sample size, the t-critical value, the standard error, the margin of error, and the low/high endpoints of a 95% condifence interval

omega %&gt;%
  group_by(gender) %&gt;%
  summarise(mean = mean(salary),
            SD = sd(salary),
            sample_size = n(),
            t_critical = qt(0.975, sample_size -1),
            SE = SD/sqrt(sample_size),
            margin_of_error = SE*t_critical,
            lower_ci = mean - margin_of_error,
            upper_ci = mean + margin_of_error)</code></pre>
<pre><code>## # A tibble: 2 x 9
##   gender   mean    SD sample_size t_critical    SE margin_of_error lower_ci
##   &lt;chr&gt;   &lt;dbl&gt; &lt;dbl&gt;       &lt;int&gt;      &lt;dbl&gt; &lt;dbl&gt;           &lt;dbl&gt;    &lt;dbl&gt;
## 1 female 64543. 7567.          26       2.06 1484.           3056.   61486.
## 2 male   73239. 7463.          24       2.07 1523.           3151.   70088.
## # ... with 1 more variable: upper_ci &lt;dbl&gt;</code></pre>
<blockquote>
<p>From the above table, we find that for almost all the statistics (including min, Q1, median, Q3, max, mean), males have higher salary than females.</p>
</blockquote>
<blockquote>
<p>Besides, the mean salary of females is in the range [61486, 67599] and the mean salary of males is in the range [70088, 76390]. There is no overlap between these two confidence intervals.This would allow us to reject the null hypothesis, but we will carry out hypothesis testing anyway and analyse the relationships between all the remaining factors.</p>
</blockquote>
<p>Then, we use <code>t.test()</code> and the simulation method from the <code>infer</code> package to run a hypothesis testing, assuming as a null hypothesis that the mean difference in salaries is zero, or that, on average, men and women make the same amount of money.</p>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(salary~gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  salary by gender
## t = -4, df = 48, p-value = 2e-04
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -12973  -4420
## sample estimates:
## mean in group female   mean in group male 
##                64543                73239</code></pre>
<pre class="r"><code># hypothesis testing using infer package
male_mean &lt;- omega %&gt;%
  filter(gender == &quot;male&quot;) %&gt;%
  summarize(male_mean = mean(salary))

female_mean &lt;- omega %&gt;%
  filter(gender == &quot;female&quot;) %&gt;%
  summarize(female_mean = mean(salary))

obs_diff &lt;- female_mean - male_mean

stimulated &lt;- omega %&gt;%
  specify(salary~gender) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000,
           type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;female&quot;, &quot;male&quot;))

stimulated %&gt;%
  get_pvalue(obs_stat = obs_diff[1,1],
            direction = &quot;both&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<blockquote>
<p>In both t.test and bootstrap hypothesis test, the p-value generated is less than the alpha value of 0.05. Therefore, we reject the null hypothesis and conclude that there is a statistically significant difference in salary between male and female employees in Omega Group.</p>
</blockquote>
</div>
<div id="relationship-experience---gender" class="section level2">
<h2>Relationship Experience - Gender</h2>
<p>At the board meeting, someone raised the issue that there was indeed a substantial difference between male and female salaries, but that this was attributable to other reasons such as differences in experience.</p>
<p>A questionnaire send out to the 50 executives in the sample reveals that the average experience of the men is approximately 21 years, whereas the women only have about 7 years experience on average (see table below).</p>
<pre class="r"><code># Summary Statistics of salary by gender
favstats (experience ~ gender, data=omega)</code></pre>
<pre><code>##   gender min    Q1 median   Q3 max  mean    sd  n missing
## 1 female   0  0.25    3.0 14.0  29  7.38  8.51 26       0
## 2   male   1 15.75   19.5 31.2  44 21.12 10.92 24       0</code></pre>
<p>Based on this evidence, we also use the above two methods to run hypothesis testing. Our null hypothesis is that there is no significant difference between the experience of the male and female executives.</p>
<pre class="r"><code># hypothesis testing using t.test() 
t.test(experience~gender, data = omega)</code></pre>
<pre><code>## 
##  Welch Two Sample t-test
## 
## data:  experience by gender
## t = -5, df = 43, p-value = 1e-05
## alternative hypothesis: true difference in means is not equal to 0
## 95 percent confidence interval:
##  -19.35  -8.13
## sample estimates:
## mean in group female   mean in group male 
##                 7.38                21.12</code></pre>
<pre class="r"><code># hypothesis testing using infer package
male_exp &lt;- omega %&gt;%
  filter(gender == &quot;male&quot;) %&gt;%
  summarize(male_mean = mean(experience))

female_exp &lt;- omega %&gt;%
  filter(gender == &quot;female&quot;) %&gt;%
  summarize(female_mean = mean(experience))

obs_diff &lt;- female_exp - male_exp

stimulated &lt;- omega %&gt;%
  specify(experience~gender) %&gt;%
  hypothesize(null = &quot;independence&quot;) %&gt;%
  generate(reps = 1000,
           type = &quot;permute&quot;) %&gt;%
  calculate(stat = &quot;diff in means&quot;,
            order = c(&quot;female&quot;, &quot;male&quot;))

stimulated %&gt;%
  get_pvalue(obs_stat = obs_diff[1,1],
            direction = &quot;both&quot;)</code></pre>
<pre><code>## # A tibble: 1 x 1
##   p_value
##     &lt;dbl&gt;
## 1       0</code></pre>
<blockquote>
<p>In both t.test and bootstrap hypothesis test, the p-value generated is less than the alpha value of 0.05. Therefore, we reject the null hypothesis and conclude that there is a statistically significant difference in experience between male and female employees in Omega Group.</p>
</blockquote>
</div>
<div id="relationship-salary---experience" class="section level2">
<h2>Relationship Salary - Experience</h2>
<p>Someone at the meeting argues that clearly, a more thorough analysis of the relationship between salary and experience is required before any conclusion can be drawn about whether there is any gender-based salary discrimination in the company.</p>
<p>So we analyse the relationship between salary and experience and draw a scatterplot to visually inspect the data.</p>
<pre class="r"><code>ggplot(omega, 
       aes(x = experience, y = salary)) + 
  geom_point(aes(colour = gender)) + 
  geom_smooth() + 
  labs(title = &quot;Does experience affect salary?&quot;,
       x = &quot;Years of experience&quot;,
       y = &quot;Salary ($)&quot;) + 
  theme_base()</code></pre>
<p><img src="index_files/figure-html/salary_exp_scatter-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>From the scatterplot shown above, there seems to be a positive relationship between years of experience and salary, although the difference in salary appears to decrease at higher levels of experience.</p>
</blockquote>
</div>
<div id="check-correlations-between-the-data" class="section level2">
<h2>Check correlations between the data</h2>
<p>We use <code>GGally:ggpairs()</code> to create a scatterplot and correlation matrix. Essentially, we change the order our variables will appear in and have the dependent variable (Y), salary, as last in our list. We then pipe the dataframe to <code>ggpairs()</code> with <code>aes</code> arguments to colour by <code>gender</code> and make ths plots somewhat transparent (<code>alpha  = 0.3</code>).</p>
<pre class="r"><code>omega %&gt;% 
  #order variables they will appear in ggpairs()
  select(gender, experience, salary) %&gt;% 
  ggpairs(aes(colour=gender, alpha = 0.3)) + 
  theme_bw()</code></pre>
<p><img src="index_files/figure-html/ggpairs-1.png" width="648" style="display: block; margin: auto;" /></p>
<blockquote>
<p>The salary vs experience scatterplot shows that the majority of women in the sample have a comparable salary to men with the same experience level.</p>
</blockquote>
<blockquote>
<p>The majority of women in the sample have experience between 0 and 20 years, whereas the approximate range of experience for most men is between 10 and 35 years. In the previous analysis, we concluded that there is a statistically significant difference between the levels of experience for both genders. This chart further confirms what we were seeing before. Women seem to end their careers earlier, at least within the given sample.</p>
</blockquote>
</div>
</div>
<div id="challenge-1-reproducing-yield-curve" class="section level1">
<h1>Challenge 1: Reproducing Yield Curve</h1>
<p>##Parable</p>
<p><img src="C:/Users/User/Desktop/Arun_Website/images/yield_curve_parable.jpg" width="100%" style="display: block; margin: auto;" /></p>
<p>###FRED</p>
<pre class="r"><code># Get a list of FRED codes for US rates and US yield curve; choose monthly frequency
# to see, eg., the 3-month T-bill https://fred.stlouisfed.org/series/TB3MS
tickers &lt;- c(&#39;TB3MS&#39;, # 3-month Treasury bill (or T-bill)
             &#39;TB6MS&#39;, # 6-month
             &#39;GS1&#39;,   # 1-year
             &#39;GS2&#39;,   # 2-year, etc....
             &#39;GS3&#39;,
             &#39;GS5&#39;,
             &#39;GS7&#39;,
             &#39;GS10&#39;,
             &#39;GS20&#39;,
             &#39;GS30&#39;)  #.... all the way to the 30-year rate

# Turn  FRED codes to human readable variables
myvars &lt;- c(&#39;3-Month Treasury Bill&#39;,
            &#39;6-Month Treasury Bill&#39;,
            &#39;1-Year Treasury Rate&#39;,
            &#39;2-Year Treasury Rate&#39;,
            &#39;3-Year Treasury Rate&#39;,
            &#39;5-Year Treasury Rate&#39;,
            &#39;7-Year Treasury Rate&#39;,
            &#39;10-Year Treasury Rate&#39;,
            &#39;20-Year Treasury Rate&#39;,
            &#39;30-Year Treasury Rate&#39;)

maturity &lt;- c(&#39;3m&#39;, &#39;6m&#39;, &#39;1y&#39;, &#39;2y&#39;,&#39;3y&#39;,&#39;5y&#39;,&#39;7y&#39;,&#39;10y&#39;,&#39;20y&#39;,&#39;30y&#39;)

# by default R will sort these maturities alphabetically; but since we want
# to keep them in that exact order, we recast maturity as a factor 
# or categorical variable, with the levels defined as we want
maturity &lt;- factor(maturity, levels = maturity)

# Create a lookup dataset
mylookup&lt;-data.frame(symbol=tickers,var=myvars, maturity=maturity)
# Take a look:
mylookup %&gt;% 
  knitr::kable()</code></pre>
<table>
<thead>
<tr>
<th style="text-align:left;">
symbol
</th>
<th style="text-align:left;">
var
</th>
<th style="text-align:left;">
maturity
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
TB3MS
</td>
<td style="text-align:left;">
3-Month Treasury Bill
</td>
<td style="text-align:left;">
3m
</td>
</tr>
<tr>
<td style="text-align:left;">
TB6MS
</td>
<td style="text-align:left;">
6-Month Treasury Bill
</td>
<td style="text-align:left;">
6m
</td>
</tr>
<tr>
<td style="text-align:left;">
GS1
</td>
<td style="text-align:left;">
1-Year Treasury Rate
</td>
<td style="text-align:left;">
1y
</td>
</tr>
<tr>
<td style="text-align:left;">
GS2
</td>
<td style="text-align:left;">
2-Year Treasury Rate
</td>
<td style="text-align:left;">
2y
</td>
</tr>
<tr>
<td style="text-align:left;">
GS3
</td>
<td style="text-align:left;">
3-Year Treasury Rate
</td>
<td style="text-align:left;">
3y
</td>
</tr>
<tr>
<td style="text-align:left;">
GS5
</td>
<td style="text-align:left;">
5-Year Treasury Rate
</td>
<td style="text-align:left;">
5y
</td>
</tr>
<tr>
<td style="text-align:left;">
GS7
</td>
<td style="text-align:left;">
7-Year Treasury Rate
</td>
<td style="text-align:left;">
7y
</td>
</tr>
<tr>
<td style="text-align:left;">
GS10
</td>
<td style="text-align:left;">
10-Year Treasury Rate
</td>
<td style="text-align:left;">
10y
</td>
</tr>
<tr>
<td style="text-align:left;">
GS20
</td>
<td style="text-align:left;">
20-Year Treasury Rate
</td>
<td style="text-align:left;">
20y
</td>
</tr>
<tr>
<td style="text-align:left;">
GS30
</td>
<td style="text-align:left;">
30-Year Treasury Rate
</td>
<td style="text-align:left;">
30y
</td>
</tr>
</tbody>
</table>
<pre class="r"><code>df &lt;- tickers %&gt;% tidyquant::tq_get(get=&quot;economic.data&quot;, 
                   from=&quot;1960-01-01&quot;)   # start from January 1960

glimpse(df)</code></pre>
<pre><code>## Rows: 6,774
## Columns: 3
## $ symbol &lt;chr&gt; &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS&quot;, &quot;TB3MS...
## $ date   &lt;date&gt; 1960-01-01, 1960-02-01, 1960-03-01, 1960-04-01, 1960-05-01,...
## $ price  &lt;dbl&gt; 4.35, 3.96, 3.31, 3.23, 3.29, 2.46, 2.30, 2.30, 2.48, 2.30, ...</code></pre>
<p>###Joining data</p>
<pre class="r"><code>yield_curve &lt;-left_join(df,mylookup,by=&quot;symbol&quot;) </code></pre>
<div id="plotting-the-yield-curve" class="section level2">
<h2>Plotting the yield curve</h2>
<div id="yields-on-us-rates-by-duration-since-1960" class="section level3">
<h3>Yields on US rates by duration since 1960</h3>
<p><img src="index_files/figure-html/yield_curve_1-1.png" width="100%" style="display: block; margin: auto;" /></p>
</div>
<div id="monthly-yields-on-us-rates-by-duration-since-1999-on-a-year-by-year-basis" class="section level3">
<h3>Monthly yields on US rates by duration since 1999 on a year-by-year basis</h3>
<pre class="r"><code>yieldyear &lt;- yield_curve %&gt;% 
  clean_names() %&gt;% 
  mutate (year = year(date),
          month = lubridate::month(date, label = TRUE),
          week = isoweek(date)) %&gt;% filter(year &gt; 1998)

yieldyear$year = as.factor(yieldyear$year)




r &lt;- ggplot(yieldyear, aes(x=maturity, y=price, group = date, color = year)) + geom_line() + facet_wrap(~year) + labs(title = &quot;US Yield Curve&quot;, caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;, x = &quot;Maturity&quot;, y = &quot;Yield (%)&quot;) + theme_bw() + theme(legend.position = &quot;none&quot;)

r</code></pre>
<p><img src="index_files/figure-html/yield_curve_2-1.png" width="648" style="display: block; margin: auto;" /></p>
</div>
<div id="month-and-10-year-yields-since-1999" class="section level3">
<h3>3-month and 10-year yields since 1999</h3>
<pre class="r"><code>part3 = yield_curve %&gt;% filter(maturity == &quot;3m&quot; | maturity ==&quot;10y&quot;)

s &lt;- ggplot(part3, aes(x=date, y=price, color = maturity), group = maturity)+geom_line()+ theme_bw() + labs(title = &quot;Yields on 3-month and 10-year US Treasury rates since 1999&quot;, caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;, x = &quot;&quot;, y = &quot;%&quot;) + scale_y_continuous( limits=c(0,7)) + scale_x_date(limits = as.Date(c(&#39;1999-01-01&#39;,&#39;2020-01-01&#39;)))

s</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-17-1.png" width="648" style="display: block; margin: auto;" /></p>
<p>According to <a href="https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States">Wikipedia’s list of recession in the United States</a>, since 1999 there have been two recession in the US: between Mar 2001–Nov 2001 and between Dec 2007–June 2009. Does the yield curve seem to flatten before these recessions? Can a yield curve flattening really mean a recession is coming in the US? Since 1999, when did short-term (3 months) yield more than longer term (10 years) debt?</p>
<blockquote>
<p>Since 1999, Short term yields increased passed the ten year in 2001, 2008, and 2020. This along with graph #2 suggest that yield curve seemed to flatter (and even invert) in periods before recessions. it seems, A yield curve flattening has strong correlation with recessions. So a recession may be coming to the US.</p>
</blockquote>
</div>
<div id="getting-recession-data" class="section level3">
<h3>Getting Recession Data</h3>
<pre class="r"><code># get US recession dates after 1946 from Wikipedia 
# https://en.wikipedia.org/wiki/List_of_recessions_in_the_United_States

recessions &lt;- tibble(
  from = c(&quot;1948-11-01&quot;, &quot;1953-07-01&quot;, &quot;1957-08-01&quot;, &quot;1960-04-01&quot;, &quot;1969-12-01&quot;, &quot;1973-11-01&quot;, &quot;1980-01-01&quot;,&quot;1981-07-01&quot;, &quot;1990-07-01&quot;, &quot;2001-03-01&quot;, &quot;2007-12-01&quot;),  
  to = c(&quot;1949-10-01&quot;, &quot;1954-05-01&quot;, &quot;1958-04-01&quot;, &quot;1961-02-01&quot;, &quot;1970-11-01&quot;, &quot;1975-03-01&quot;, &quot;1980-07-01&quot;, &quot;1982-11-01&quot;, &quot;1991-03-01&quot;, &quot;2001-11-01&quot;, &quot;2009-06-01&quot;) 
  )  %&gt;% 
  mutate(From = ymd(from), 
         To=ymd(to),
         duration_days = To-From)

recessions</code></pre>
<pre><code>## # A tibble: 11 x 5
##    from       to         From       To         duration_days
##    &lt;chr&gt;      &lt;chr&gt;      &lt;date&gt;     &lt;date&gt;     &lt;drtn&gt;       
##  1 1948-11-01 1949-10-01 1948-11-01 1949-10-01 334 days     
##  2 1953-07-01 1954-05-01 1953-07-01 1954-05-01 304 days     
##  3 1957-08-01 1958-04-01 1957-08-01 1958-04-01 243 days     
##  4 1960-04-01 1961-02-01 1960-04-01 1961-02-01 306 days     
##  5 1969-12-01 1970-11-01 1969-12-01 1970-11-01 335 days     
##  6 1973-11-01 1975-03-01 1973-11-01 1975-03-01 485 days     
##  7 1980-01-01 1980-07-01 1980-01-01 1980-07-01 182 days     
##  8 1981-07-01 1982-11-01 1981-07-01 1982-11-01 488 days     
##  9 1990-07-01 1991-03-01 1990-07-01 1991-03-01 243 days     
## 10 2001-03-01 2001-11-01 2001-03-01 2001-11-01 245 days     
## 11 2007-12-01 2009-06-01 2007-12-01 2009-06-01 548 days</code></pre>
</div>
<div id="spread-graph-replication" class="section level3">
<h3>Spread Graph Replication</h3>
<pre class="r"><code>#Setting Up Spread Columns
yieldspread3  = yield_curve %&gt;%  filter( maturity == &quot;3m&quot;) 

yieldspread10 =  yield_curve %&gt;%  filter(maturity == &quot;10y&quot;)

yielddiff = left_join(yieldspread3, yieldspread10, by = &quot;date&quot;)



yieldspread = yielddiff %&gt;% select(date, price.x, price.y)

yieldspread$spread = yielddiff$price.y - yielddiff$price.x

yieldspread$date = as.Date(yieldspread$date)

# mutating for ribbons
yieldspread = yieldspread %&gt;% mutate(z=ifelse(spread&gt;0,spread,0))

#Graphing
h &lt;- ggplot(yieldspread, aes(x=date, y=spread)) + geom_line() + labs(title = &quot;US Yield Curve&quot;, caption = &quot;Source: St. Louis Federal Reserve Economic Database (FRED)&quot;, x = &quot;&quot;, y = &quot;Difference(10year - 3month) yield in %&quot;) + theme_bw() + geom_hline(aes(yintercept = 0)) 

#adding Blue and Red Ribbons


h= h+geom_ribbon(aes(ymin=0,ymax=spread, group = 1), fill=&quot;#9fb8ef&quot;, color=&quot;black&quot;) + geom_ribbon(aes(ymin=spread, ymax=z), fill=&quot;#eda1a1&quot;, color=&quot;black&quot;) 
  
h</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-18-1.png" width="648" style="display: block; margin: auto;" /></p>
<pre class="r"><code>#adding grey boxes for recession dates
h = h + geom_rect(data=recessions, aes(NULL,NULL, xmin = From, xmax = To),
            ymin=-10,ymax=10, colour=&quot;grey&quot;, size=0.5, alpha=0.2)   + scale_x_date(limits = as.Date(c(&#39;1960-01-01&#39;,&#39;2021-01-01&#39;)))          
         


#adding geom_rug

h+geom_rug(aes(color = spread&gt;0), position = &quot;jitter&quot;,sides = &#39;b&#39;,size = 0.0001) + scale_color_manual(values = c(&quot;#eda1a1&quot;, &quot;#9fb8ef&quot;))</code></pre>
<p><img src="index_files/figure-html/unnamed-chunk-18-2.png" width="648" style="display: block; margin: auto;" /></p>
</div>
</div>
</div>
<div id="challenge-2gdp-components-over-time-and-among-countries" class="section level1">
<h1>Challenge 2:GDP components over time and among countries</h1>
<p>At the risk of oversimplifying things, the main components of gross domestic product, GDP are personal consumption (C), business investment (I), government spending (G) and net exports (exports - imports). You can read more about GDP and the different approaches in calculating at the <a href="https://en.wikipedia.org/wiki/Gross_domestic_product">Wikipedia GDP page</a>.</p>
<p>The GDP data we will look at is from the <a href="https://unstats.un.org/unsd/snaama/Downloads">United Nations’ National Accounts Main Aggregates Database</a>, which contains estimates of total GDP and its components for all countries from 1970 to today. We will look at how GDP and its components have changed over time, and compare different countries and how much each component contributes to that country’s GDP. The file we will work with is <a href="http://unstats.un.org/unsd/amaapi/api/file/6">GDP and its breakdown at constant 2010 prices in US Dollars</a> and it has already been saved in the Data directory. Have a look at the Excel file to see how it is structured and organised</p>
<pre class="r"><code>UN_GDP  &lt;-  read_excel(here::here(&quot;data&quot;, &quot;Download-GDPconstant-USD-countries.xls&quot;), # Excel filename
                sheet=&quot;Download-GDPconstant-USD-countr&quot;, # Sheet name
                skip=1) # Number of rows to skip


GDP_tidy&lt;- UN_GDP %&gt;% 
  
  pivot_longer(cols = 4:51, names_to = &#39;Year&#39;, values_to = &#39;Value&#39;) %&gt;% 
  filter(IndicatorName %in% c(&#39;Gross capital formation&#39;,
                    &#39;Exports of goods and services&#39;,
                    &#39;Imports of goods and services&#39;,
                    &#39;General government final consumption expenditure&#39;,
                    &#39;Household consumption expenditure (including Non-profit institutions serving households)&#39;,
                    &#39;Gross Domestic Product (GDP)&#39;)) %&gt;%
  mutate(Value = Value/1e9) %&gt;%
  
   # renaming our indicators
  mutate(IndicatorName = case_when(IndicatorName == &#39;Gross capital formation&#39; ~ &#39;Gross capital formation&#39;,
                 IndicatorName == &#39;Gross Domestic Product (GDP)&#39; ~ &#39;GDP&#39;,
                 IndicatorName == &#39;Imports of goods and services&#39; ~ &#39;Imports&#39;,
                 IndicatorName == &#39;Exports of goods and services&#39; ~ &#39;Exports&#39;,
                 IndicatorName == &#39;General government final consumption expenditure&#39; ~ &#39;Government expenditure&#39;,
                 IndicatorName == &#39;Household consumption expenditure (including Non-profit institutions serving households)&#39; ~ &#39;Household expenditure&#39;))

glimpse(GDP_tidy)</code></pre>
<pre><code>## Rows: 63,072
## Columns: 5
## $ CountryID     &lt;dbl&gt; 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4,...
## $ Country       &lt;chr&gt; &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghanistan&quot;, &quot;Afghani...
## $ IndicatorName &lt;chr&gt; &quot;Household expenditure&quot;, &quot;Household expenditure&quot;, &quot;Ho...
## $ Year          &lt;chr&gt; &quot;1970&quot;, &quot;1971&quot;, &quot;1972&quot;, &quot;1973&quot;, &quot;1974&quot;, &quot;1975&quot;, &quot;1976...
## $ Value         &lt;dbl&gt; 5.07, 4.84, 4.70, 5.21, 5.59, 5.65, 5.68, 6.15, 6.30,...</code></pre>
<p>First, can you produce this plot?</p>
<p><img src="C:/Users/User/Desktop/Arun_Website/images/gdp1.png" width="100%" style="display: block; margin: auto;" /><img src="index_files/figure-html/gdp_1-2.png" width="100%" style="display: block; margin: auto;" /></p>
<blockquote>
<p>What is the % difference between what you calculated as GDP and the GDP figure included in the dataframe?</p>
</blockquote>
<pre><code>## Mean difference between calculated and given GDPs:
##  0.00398</code></pre>
<p>Perhaps this mean difference arises from reporting standards and currency rates, resulting in different calculations for each country.</p>
<p>Secondly, recall that GDP is the sum of Household Expenditure (Consumption <em>C</em>), Gross Capital Formation (business investment <em>I</em>), Government Expenditure (G) and Net Exports (exports - imports). Even though there is an indicator <code>Gross Domestic Product (GDP)</code> in your dataframe, I would like you to calculate it given its components discussed above.</p>
<p><img src="C:/Users/User/Desktop/Arun_Website/images/gdp2.png" width="100%" style="display: block; margin: auto;" /><img src="index_files/figure-html/gdp_3-2.png" width="100%" style="display: block; margin: auto;" /></p>
<blockquote>
<p>What is this last chart telling you? Can you explain in a couple of paragraphs the different dynamic among these three countries?</p>
</blockquote>
<p>Germany is the only country in the list (and one of few globally) that exhibits a clear, consistent trade surplus, primarily due to strong exports of vehicles and other machinery. This surplus has been labelled as ‘toxic’ by many, who regard it as a liability rather than an asset - even Donald Trump!</p>
<p>From the graph it is also clear to see that India’s GDP has historically been dependent on household expenditure, but this reliance has been declining in recent years, at the expense of investment. Even before COVID-19 struck, India’s household consumer demand has been vulnerable and unpredictable because of skewed occupation demographics and its clear wealth gap - India’s richest 20% of households account for 36% of consumption expenditure. On the flipside, investment in the country has risen rapidly due to favourable infrastructural factors for investors, such as energy, communication and health, and government-led FDI incentives.</p>
</div>
<div id="details" class="section level1">
<h1>Details</h1>
<ul>
<li>Who did you collaborate with: Arun Afzali, Blanche Lelouvier, Yuanmeng (Cathy) Gu, Elia Waidele, Ismaeel Haq</li>
<li>Approximately how much time did you spend on this problem set: 25 hours</li>
<li>What, if anything, gave you the most trouble: conflict of packages of plyr and dplyr, ribbons, geom_rect, hypothesis testing, colors</li>
</ul>
</div>
